#!/usr/bin/env python3

import time
import os
import sys
import subprocess
import lxml.etree as ET

def editvar(var=""):
	pathname = os.path.join(os.environ["XDG_RUNTIME_DIR"] or "/tmp", "postnoteeditvar.txt")
	with open(pathname, "w") as fil:
		fil.write(var)
	retcode = subprocess.call([os.environ["EDITOR"] or "vim", pathname])
	if retcode != 0:
		print("Aborted")
		sys.exit(1)
	with open(pathname, "r") as fil:
		return fil.read()

def E(tag, attrs={}, children=[], text=""):
	elem = ET.Element(tag, attrs)
	for child in children:
		elem.append(child)
	if text:
		elem.text = text
	return elem

def main():
	timestamp = int(time.time())
	tgtfile = os.path.join("posts", "notes", str(timestamp) + ".html")
	tree = E("html",
		children=[
			E("head", children=[
				E("meta", attrs={"name": "timestamp", "value": str(timestamp)}),
				E("meta", attrs={"name": "type", "value": "note"})]),
			ET.fromstring("<body>%s</body>" % (editvar(),))])

	with open(tgtfile, "w") as fil:
		fil.write("<!DOCTYPE html>")
		fil.write(ET.tostring(tree, encoding="unicode"))
		print("Wrote", tgtfile)

if __name__ == "__main__":
	main()
